trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Despliegue automatizado con Terraform'
  inputs:
    azureSubscription: 'Conexion-Lab-Azure-RG' # Usamos la conexión que creaste en el paso anterior
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "0. Instalando Terraform..."
      wget https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
      unzip terraform_1.8.3_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      
      echo "1. Inicializando Terraform..."
      terraform init
      
      echo "2. Validando código..."
      terraform validate
      
      echo "3. Desplegando infraestructura..."
      terraform apply -auto-approve -lock=false